### ISSUE TITLE
Fitbit Sense stuck "Connecting..."  when enabling Developer Bridge

### ISSUE THREAD

**Issue by mikepsinn** [Fitbit/developer-bridge#163]
It says "Connecting..." for about 60 seconds and then it gives up and the little switch switches back to the off position.  I've tried about 10 times and restarted the watch several times. 

I have a Wifi connection and everything else works.  I'm able to see my phone in Fitbit Studio https://studio.fitbit.com/projects/nvybrv/editor but not my Fitbit Sense. 

The Sense version is 44.128.1.142

What should I do?  Thanks! :D

**Comment by Hexxeh** [comment]
Our GitHub project issue trackers are intended for issues relating to the development of the tools in those repos. If you're still having issues, please try another support channel such as our forum (https://community.fitbit.com/t5/SDK-Development/bd-p/sdk) or Discord.
