### ISSUE TITLE
What's wrong with npm

### ISSUE THREAD

**Issue by vladstitov** [Fitbit/developer-bridge#63]
First line of instructions makes me worry
"1.Install node and yarn (npm won't work)"
then longer you delay with this bug then harder will be fix it.

**Comment by Hexxeh** [comment]
There's nothing wrong with npm: we just have package scripts configured to use yarn explicitly and we have lerna (the tool we use to manage this monorepo) configured to use yarn.

yarn is our package manager of choice, and so we check `yarn.lock` files into our repos for reproducible unit tests and development environments amongst developers. There's not really anything for us to fix in that respect: not until the JS ecosystem lands on a common format at least.
